### ISSUE TITLE
Revised value retrieval + stoich interaction

### ISSUE THREAD

**Issue by petosa** [psi4/mongo_qcdb#1]
As we discussed last week, I will be implementing the ability to specify which field to pull with a `get_data` function call. We mentioned a flag, which I call `do_stoich` to determine whether the aggregation of values should be multiplied by the stoichiometry weights and then summed. My question is, if I have `do_stoich` as false, what operation do I perform on the values I retrieve?

For reference, here is my `get_data` revised header:
```python
# Returns a single data value from database
    # Field: The name of the field in Page that you retrieve
    # DB: The name of the DB you want to query
    # rxn: The name of the reaction to query
    # Method: Method to use to query a Page
    # do_stoich: Flag whether or not to sum based on stoich
    # debug_level: 0-2 verbosity
  def get_value(self, field, db, rxn, stoich, method, do_stoich=True, debug_level=1):
```

For example, let's say I'm pulling `success` fields. My `get_value` function has three molecules under stoichiometry/cp, so I look up each with the `method` to get a `page`. The success fields of each are `True`, `True`, and `False`. I imagine `do_stoich=False` in this case as the values are not numerical. What then do I return from this function?

As a follow up, when the return field is `return_value`, we already decided to have a fallback procedure that does a lookup in reaction_results/cp. What should happen if the `field` is not `return_value` (say, `success` instead)? Do I just return `None`?

Thanks, if any of this is unclear let me know.

**Comment by dgasmith** [comment]
We have moved passed this I believe.
